music/urls.py
from django.urls import path
from .views import MusicViewer, PostMusicViewer, MusicUploadView, CommentMusicViewer, MusicListViewer

app_name = "music"

urlpatterns = [
    path('music/<int:id>/', MusicViewer.as_view(), name='music_dt'),
    path('music/comment/', CommentMusicViewer.as_view(), name='comment'),
    path('music/new/', PostMusicViewer.as_view(), name='music_new'),
    path('mp3-upload/', MusicUploadView.as_view(), name="mp3_upload"),

]

second/music/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .views import MusicViewSet, ReactViewSet, MusicsViewSet, MusicsViewV2, MusicViewV2

app_name = "music_api"

router = SimpleRouter()

#router.register("musics", MusicsViewSet, basename="musics")
router.register("reacts", ReactViewSet, basename="reacts")

urlpatterns = router.urls
urlpatterns += [
    path("music/", MusicsViewV2.as_view(), name="musics"),
    path("music/<int:id>/", MusicViewV2.as_view(), name="music"),

]

second/music/urls.py
from django.urls import path
from .views import MusicViewer, PostMusicViewer, MusicUploadView, CommentMusicViewer, VoteMusicViewer, \
    ListenMusicViewer, UpdateMusicViewer, DeleteMusic, DeleteReactView

app_name = "music"

urlpatterns = [
    path('music/<int:id>/', MusicViewer.as_view(), name='music_dt'),
    path(r'music/<int:id>/<int:p>/', MusicViewer.as_view(), name='music_dt'),
    path('music/listen/', ListenMusicViewer.as_view(), name='listen'),
    path('music/vote/', VoteMusicViewer.as_view(), name='vote'),
    path('music/comment/', CommentMusicViewer.as_view(), name='comment'),
    path('music/new/', PostMusicViewer.as_view(), name='music_new'),
    path('music/update/<int:id>/', UpdateMusicViewer.as_view(), name='music_update'),
    path('music/delete/comment/', DeleteReactView.as_view(), name='react_del'),
    path('music/delete/<int:id>/', DeleteMusic.as_view(), name='music_del'),
    path('mp3-upload/', MusicUploadView.as_view(), name="mp3_upload"),

]

user/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserRedirectView,
    UserUpdateView, LogoutView, LoginView,
)

app_name = "user"

urlpatterns = [
    path("redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("update/", view=UserUpdateView.as_view(), name="update"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("user/<str:username>/", view=UserDetailView.as_view(), name="detail"),

]

music/models.py
from django.db import models


from user.models import User


class MusicModel(models.Model):
    title = models.CharField(max_length=200, unique=True, help_text="Unique Title of the music")
    file = models.FileField(upload_to="music/", help_text="Music's file")
    description = models.CharField(max_length=1500)


class MusicLover(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=100)


class ReactModel(models.Model):
    music = models.ForeignKey(MusicModel, on_delete=models.CASCADE, default=1)
    comment = models.CharField(null=True, max_length=1100)
    owner = models.ForeignKey(MusicLover, on_delete=models.CASCADE)

music/views.py
from django.shortcuts import redirect
from djvue.views import FileUploadView
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import MusicModel, ReactModel
from .serializers import MusicUploadSerializer, MusicSerializer, ReactSerializer
from user.models import User


class MusicListViewer(APIView):
    """
    A simple view to show music list
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    template_name = 'musiclist.html'

    def get(self, request, *args, **kwargs):
        try:
            user = request.session["user"]
        except KeyError:
            return redirect('user:login')

        musics = MusicModel.objects.all()
        data = {"musics": musics}
        return Response(data)


class MusicUploadView(FileUploadView):
    """
    Helper view to upload mp3 music file
    """
    permission_classes = (AllowAny,)
    serializer_class = MusicUploadSerializer


class MusicViewer(APIView):
    """
    Main view to show the music with comments functionality
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    permission_classes = (AllowAny,)
    template_name = "music.html"

    def get(self, request, *args, **kwargs, ):
        try:
            user = request.session["user"]
        except KeyError:
            return redirect('user:login')

        serializer = ReactSerializer
        id = self.kwargs['id']
        music = MusicModel.objects.get(id=id)
        comments = ReactModel.objects.all().filter(music=id)
        user = User.objects.get(username=request.session["user"])

        data = {
            "music": music,
            "serializer": serializer,
            "comments": comments,
            "user": user
        }
        #print(data)
        return Response(data)


class CommentMusicViewer(CreateAPIView):
    """
    API view for commenting on the music
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    serializer_class = ReactSerializer

    def post(self, request, *args, **kwargs):
        try:
            user = request.session["user"]
        except KeyError:
            return redirect('user:login')

        serializer = ReactSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"msg": "serializer.data"})


class PostMusicViewer(CreateAPIView):
    """
    Create Music view API
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    serializer_class = MusicSerializer
    permission_classes = (AllowAny,)
    template_name = "new_music.html"

    def get(self, request, *args, **kwargs):
        try:
            user = request.session["user"]
        except KeyError:
            return redirect('user:login')

        serializer = self.get_serializer()
        data = {
            "serializer": serializer
        }
        return Response(data)

second/music/api/views.py
from rest_framework import generics
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import get_object_or_404
from rest_framework.mixins import RetrieveModelMixin, ListModelMixin, UpdateModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer, BrowsableAPIRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet, ModelViewSet
from .serializers import MusicAPISerializer, ReactAPISerializer

from music.models import ReactModel, MusicModel


class MusicsViewV2(generics.ListCreateAPIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [TokenAuthentication]
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]
    serializer_class = MusicAPISerializer
    queryset = MusicModel.objects.all()


class MusicViewV2(generics.RetrieveDestroyAPIView):
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]
    permission_classes = [IsAuthenticated]
    serializer_class = MusicAPISerializer
    lookup_field = "id"
    queryset = MusicModel.objects.all()


class MusicsViewSet(ModelViewSet):
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]
    serializer_class = MusicAPISerializer
    queryset = MusicModel.objects.all()
    lookup_field = "id"


class MusicViewSet(APIView):
    queryset = MusicModel.objects.all()
    lookup_field = "id"
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]
    serializer_class = MusicAPISerializer

    def get(self, request, id):
        serializer_context = {
            'request': request,
        }
        music = get_object_or_404(MusicModel, id=id)
        data = MusicAPISerializer(music, many=False, context=serializer_context).data
        return Response(data)


class ReactViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]
    serializer_class = ReactAPISerializer
    queryset = ReactModel.objects.all()

second/music/views.py
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models.aggregates import Count, Sum
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.list import ListView
from djvue.views import FileUploadView
from rest_framework.exceptions import PermissionDenied as per_denied

from rest_framework.generics import CreateAPIView, UpdateAPIView, DestroyAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication
from .api.serializers import VoteSerializer, ListenSerializer
from .models import MusicModel, ReactModel, MusicLover
from music.api.serializers import MusicUploadSerializer, MusicSerializer, ReactSerializer


class MusicListViewer(ListView):
    """
    A simple view to show music list
    """
    model = MusicModel
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is None:
            return MusicModel.objects.all().annotate(views=Count('listeners')).order_by('-views')
        else:
            return MusicModel.objects.filter(title__contains=query).annotate(views=Count('listeners')).order_by(
                '-views')

    def get_context_data(self, **kwargs):
        if not self.request.user.is_authenticated:
            raise PermissionDenied

        query = self.request.GET.get('query', '')
        context = super().get_context_data(**kwargs)
        all_music = MusicModel.objects.all().exclude(votemodel=None).annotate(votes=Sum('votemodel__value')).order_by(
            '-votes')
        mymusic = MusicModel.objects.filter(created_by__user=self.request.user).annotate(
            views=Count('listeners')).order_by(
            '-views')

        context['search_query'] = query
        context['musics'] = self.object_list
        context['allmusics'] = all_music[:5]
        context['mymusic'] = mymusic
        return context


class CsrfExemptSessionAuthentication(SessionAuthentication):
    def enforce_csrf(self, request):
        return


class MusicUploadView(FileUploadView):
    """
    Helper view to upload mp3 music file
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    permission_classes = (IsAuthenticated,)
    serializer_class = MusicUploadSerializer
    authentication_classes = [CsrfExemptSessionAuthentication]


class MusicViewer(APIView):
    """
    Main view to show the music with comments functionality
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    permission_classes = (IsAuthenticated,)
    template_name = "music.html"

    def get(self, request, *args, **kwargs, ):
        serializer = ReactSerializer
        voteserializer = VoteSerializer
        id = self.kwargs['id']
        try:
            page = self.kwargs['p']
        except KeyError:

            page = 1

        music = get_object_or_404(MusicModel, id=id)
        comments = ReactModel.objects.all().filter(music=id)
        p_comments = Paginator(comments, 10)

        page_obj = p_comments.get_page(page)
        user = User.objects.get(username=request.user)
        listen = music.get_listen()
        try:
            lover = MusicLover.objects.get(user=user)

        except MusicLover.DoesNotExist:
            return redirect('user:login')

        update = None
        if music.created_by == lover:
            update = 1

        data = {
            "music": music,
            "serializer": serializer,
            "comments": page_obj,
            "user": lover,
            "update": update,
            "listen": listen,
            "votes": music.get_votes(),
            "voteserializer": voteserializer
        }
        return Response(data)


class CommentMusicViewer(CreateAPIView):
    """
    API view for commenting on the music
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    serializer_class = ReactSerializer
    permission_classes = (IsAuthenticated,)
    authentication_classes = [CsrfExemptSessionAuthentication]

    def post(self, request, *args, **kwargs):
        serializer = ReactSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"msg": "serializer.data"})


class VoteMusicViewer(CreateAPIView):
    """
    API view for commenting on the music
    """
    renderer_classes = [JSONRenderer]
    serializer_class = VoteSerializer
    permission_classes = (AllowAny,)
    authentication_classes = [CsrfExemptSessionAuthentication]

    def post(self, request, *args, **kwargs):
        serializer = VoteSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"msg": "request.data"})


class ListenMusicViewer(CreateAPIView):
    """
    API view for save listening requests on music
    """
    renderer_classes = [JSONRenderer]
    serializer_class = ListenSerializer
    permission_classes = (AllowAny,)
    authentication_classes = [CsrfExemptSessionAuthentication]

    def post(self, request, *args, **kwargs):
        serializer = ListenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"msg": "request.data"})


class PostMusicViewer(CreateAPIView):
    """
    Create Music view API
    """
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    serializer_class = MusicSerializer
    permission_classes = (IsAuthenticated,)
    template_name = "new_music.html"
    authentication_classes = [CsrfExemptSessionAuthentication]

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        lover = MusicLover.objects.get(user=request.user)
        data = {
            "user": lover,
            "serializer": serializer
        }
        return Response(data)


class DeleteMusic(APIView):
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    permission_classes = (IsAuthenticated,)
    authentication_classes = [CsrfExemptSessionAuthentication]

    def post(self, request, id):
        music = get_object_or_404(MusicModel, id=id)
        if request.user != music.created_by.user:
            raise per_denied('You cannot delete music not yours!')
        music.delete()
        return Response("{'msg':'done'}")


class DeleteReactView(APIView):
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    permission_classes = (IsAuthenticated,)
    authentication_classes = [CsrfExemptSessionAuthentication]
    serializer_class = ReactSerializer

    def post(self, request):
        react = get_object_or_404(ReactModel, id=request.data['id'])
        if request.user != react.owner.user:
            raise per_denied('You cannot delete music not yours!')

        react.delete()
        return Response("{'msg':'done'}")


class UpdateMusicViewer(UpdateAPIView):
    """
    update Music view API
    """
    lookup_field = 'id'
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    serializer_class = MusicSerializer
    permission_classes = (IsAuthenticated,)
    template_name = "update_music.html"
    authentication_classes = [CsrfExemptSessionAuthentication]
    queryset = MusicModel.objects.all()

    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        music = get_object_or_404(MusicModel, id=id)
        serializer = MusicSerializer(music)
        if request.user != music.created_by.user:
            raise per_denied('cannot edit music not yours!')
        data = {
            "sdata": serializer.data,
            "serializer": serializer
        }
        return Response(data)

    def post(self, request, id):
        serializer = MusicSerializer(data=request.data)
        v = serializer.is_valid(raise_exception=True)
        if v:
            serializer.save()
        return Response("{'msg':'done'}")

second/music/templates/music.html
{% extends "base1.html" %}
{% load vue_tags %}
    {% block content %}
    <h1>{{ music.title }}</h1>
    <p>{{ music.description }} <br/> added by: {{ music.created_by.display_name }} </p>
    <div>views: {{ listen }} </div>
{% if update %}<div><a href="{% url 'music:music_update' music.id %}"> Edit </a> </div>
    {% endif%}
<p>download the song from  <a href=\media\{{ music.file }} download>here</a></p>

<audio id="player" src="\media\{{ music.file }}"></audio>
<div id="listen-app" hidden>


        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

               <div class="row">
                    <div >
        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">

                        <button class="btn btn-success" style="margin-right:10px;" v-on:click="playMusic()">Play</button>
            </form>
        </validation-observer>
                    </div>
<div >
                        <button class="btn btn-danger" onclick="document.getElementById('player').pause()">Pause</button>
                        <progress id="seekbar" value="0" max="1" style="width:400px;"></progress>
                        <button class="btn btn-info" onclick="document.getElementById('player').volume += 0.1">Vol+ </button>
                        <button class="btn btn-info" onclick="document.getElementById('player').volume -= 0.1">Vol- </button>
                    </div>
               </div>
        </div>

 <div id="voting-app" hidden>


        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">
               <div class="row">
                    <div class="col-sm">
                          <h4>Votes:</h4>
                        <button name='vote' v-on:click="decrease" class="btn btn-success" value="-1">-</button>
                            {{ votes }}
                        <button v-on:click="increase" name='vote' value="1" class="btn btn-success">+</button>
                    </div>
               </div>
            </form>
        </validation-observer>
 </div>


    <ul>

    <div id="comment-app" hidden>
        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">
                <div class="row">
                    <div class="col-sm">

                         {% if comments %}
                        <div class="pagination">
                            <span class="step-links">
                                {% if comments.has_previous %}
                                    <a href="{% url 'music:music_dt' music.id comments.previous_page_number %}">Load Old Comments</a>
                                {% endif %}
                            </span>
                        </div>
                        {% endif %}
                     {% for comment in comments %}
                        <li> <div style="color:Orange; font-size=20px;">{{ comment.owner.display_name }} </div>
                            <div style="margin-left:10px; text-decoration:underline;">{{ comment.comment }} {% if comment.owner.id is user.id %}
                          <button class="btn btn-link" v-on:click="deletereact({{ comment.id }})" >Delete</button>
                          {% endif %}</div>

                      </li>
                        {% endfor %}
                         {% if comments %}
                        <div class="pagination">
                            <span class="step-links">
                                {% if comments.has_next %}
                                    <a href="{% url 'music:music_dt' music.id  comments.next_page_number %}">Load more comments</a>
                                {% endif %}
                            </span>
                        </div>
                        {% endif %}
                    </div>
                </div>

            </form>
        </validation-observer>

    </div>


    <div id="music-app" hidden>
        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">
                <div class="row">
                    <div class="col-sm">
                        {% render_vue_field serializer.comment %}
                    </div>
                </div>
                <button class="btn btn-success">Comment</button>
            </form>
        </validation-observer>

    </div>


    </ul>
    {% endblock %}

{% block extra_js %}
    <script>
        let vm = new Vue({
            el: '#music-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:comment" %}',
                    form: {
                        comment: null,
                        owner:{{ user.user.id }},
                        music:{{ music.id }},

                    }
                }
            },
            methods: {
                success(response) {
                    window.location.reload(false);
                }
            }

        })
        // remove hidden
        let appEl = document.getElementById('music-app');
        appEl.removeAttribute("hidden");

    </script>
    <script>


        let vm4 = new Vue({
            el: '#comment-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:react_del" %}',
                    form: {
                        id: null,
                        owner:{{ user.user.id }},
                        music:{{ music.id }},

                    }
                }
            },
            methods: {
                success(response) {
                    window.location.reload(false);
                },
                deletereact(val)
                {  this.form.id=val;
                }
            }

        })
        // remove hidden
        let commapp = document.getElementById('comment-app');
        commapp.removeAttribute("hidden");

    </script>

    <script>
        let vm3 = new Vue({
            el: '#listen-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:listen" %}',
                    form: {
                        first: null,
                        owner:{{ user.user.id }},
                        music:{{ music.id }},

                    }
                }
            },
            methods: {
                success(response) {
                },
                playMusic: function() {
                        document.getElementById('player').play();
                        this.form.first++;
                }


            }

        })
        // remove hidden
        let applis = document.getElementById('listen-app');
        applis.removeAttribute("hidden");

    </script>

    <script>
        let vm5 = new Vue({
            el: '#voting-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:vote" %}',
                    form: {
                        value: null,
                        owner:{{ user.user.id }},
                        music:{{ music.id }},

                    }
                }
            },
            methods: {
                success(response) {
                    window.location.reload(false);
                },
                increase: function() {
                console.log(this.form.value);
                    this.form.value++;
                },
                decrease:  function() {
                    console.log(this.form.value);
                    this.form.value--;
                }

            }

        })
        // remove hidden
        let appvot = document.getElementById('voting-app');
        appvot.removeAttribute("hidden");
    </script>

    <script>
        var player = document.getElementById('player');
        player.addEventListener("timeupdate", function() {
        var currentTime = player.currentTime;
        var duration = player.duration;
        var seekbar = document.getElementById('seekbar');
        seekbar.setAttribute("value", currentTime / duration);

        });

    </script>
{% endblock %}

second/music/templates/musiclist.html
{% extends "base1.html" %}
{% block content %}
<h1>Musics</h1>
<h3>Add New</h3> <a href="{% url 'music:music_new' %}">Here</a>
<ul>

    {% for music in musics %}
    <li>{{ music.title }} <a href={% url 'music:music_dt' id=music.id %} > view</a> </li>
    {% endfor %}
</ul>

{% endblock %}

second/music/templates/new_music.html
{% extends "base1.html" %}
{% load vue_tags %}

{% block content %}
    <div id="music-app" hidden>
        <div class="row">
            <div class="col-sm">
                <h2>New Music</h2>
            </div>
        </div>

        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">

                <div class="row">
                    <div class="col-sm">
                        {% render_vue_field serializer.title %}
                        {% render_vue_field serializer.description %}
                        {% render_vue_field serializer.file %}
                    </div>
                </div>
                <button class="btn btn-success">Save</button>
            </form>
        </validation-observer>

    </div>
{% endblock %}

{% block extra_js %}

    <script>
        let vm = new Vue({
            el: '#music-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:music_new" %}',
                    form: {
                        created_by_id:{{user.id}},
                        title: null,
                        description: null

                    }
                }
            }

        })
        // remove hidden
        let appEl = document.getElementById('music-app');
        appEl.removeAttribute("hidden");

    </script>

{% endblock %}

second/music/templates/update_music.html
{% extends "base1.html" %}
{% load vue_tags %}

{% block content %}
    <div id="music-app" hidden>
        <div class="row">
            <div class="col-sm">
                <h2>Change Music</h2>
            </div>
        </div>
        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
            <form @submit.prevent="handleSubmit(submit)" novalidate="true">
                <div class="row">
                    <div class="col-sm">
                        {% render_vue_field serializer.title %}
                        {% render_vue_field serializer.description %}

                        {% render_vue_field serializer.file %}

                    </div>
                </div>
                <button class="btn btn-success">Save</button>
            </form>
        </validation-observer>

    </div>
    <div id="del-app" hidden>
        <div class="row">
            <div class="col-sm">
                <h3>Delete Music</h3>
            </div>
        </div>
        <p v-for="error in nonFieldErrors" :key="error" class="text-danger">{( error )}</p>

        <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy" >
            <form @submit.prevent="handleSubmit(submit)" novalidate="true"  >
                <button class="btn btn-danger">Delete</button>
            </form>
        </validation-observer>

    </div>
{% endblock %}

{% block extra_js %}

    <script>
        let vd = new Vue({
            el: '#del-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:music_del" sdata.id %}',
                    form: {
                        id: {{ sdata.id }},
                    }
                }
            },
            methods: {
                success(response) {
                    window.location.reload(false);
                }
            }
        })
        // remove hidden
        let delEl = document.getElementById('del-app');
        delEl.removeAttribute("hidden");

    </script>

    <script>
        let vm = new Vue({
            el: '#music-app',
            mixins: [djVueMixin],
            data() {
                return {
                    actionURL: '{% url "music:music_update" sdata.id %}',
                    form: {
                        id: {{ sdata.id }},
                        title: '{{ sdata.title }}',
                        description: '{{ sdata.description }}',
                        created_by_id: '{{ sdata.created_by_id }}'
                    }
                }
            },
            methods: {
                success(response) {
                    window.location.reload(false);
                }
            }


        })
        // remove hidden
        let appEl = document.getElementById('music-app');
        appEl.removeAttribute("hidden");

    </script>

{% endblock %}